packages:
  - layer/*
  - packages/*
patchedDependencies:
  linkedom: patches/linkedom.patch
nodeLinker: hoisted
autoInstallPeers: false
allowBuilds:
  "@tailwindcss/oxide": true
  electron: true
  electron-window-corner-addon: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  macos-alias: true
  simple-git-hooks: true
  sqlite3: true
  unrs-resolver: true
