import type { ServerState } from '../../../types/torrent'

export const DEFAULT_SERVER_STATE: ServerState = {
  connection_status: 'disconnected',
  dht_nodes: 0,
  dl_info_data: 0,
  dl_info_speed: 0,
  dl_rate_limit: 0,
  free_space_on_disk: 0,
  global_ratio: '0.00',
  queued_io_jobs: 0,
  read_cache_hits: '0',
  read_cache_overload: '0',
  refresh_interval: 2000,
  total_buffers_size: 0,
  total_peer_connections: 0,
  total_queued_size: 0,
  total_wasted_session: 0,
  up_info_data: 0,
  up_info_speed: 0,
  up_rate_limit: 0,
  use_alt_speed_limits: false,
  use_subcategories: false,
  write_cache_overload: '0',
  alltime_dl: 0,
  alltime_ul: 0,
  average_time_queue: 0,
  queueing: false,
}
