import {
  AddedOnCellRenderer,
  CategoryCellRenderer,
  CompletionCellRenderer,
  DlspeedCellRenderer,
  DownloadedCellRenderer,
  EtaCellRenderer,
  LastActivityCellRenderer,
  NameCellRenderer,
  PeersCellRenderer,
  PriorityCellRenderer,
  ProgressCellRenderer,
  RatioCellRenderer,
  RemainingCellRenderer,
  SavePathCellRenderer,
  SeedingTimeCellRenderer,
  SeedsCellRenderer,
  SelectCellRenderer,
  SizeCellRenderer,
  StateCellRenderer,
  TagsCellRenderer,
  TimeActiveCellRenderer,
  TrackerCellRenderer,
  UploadedCellRenderer,
  UpspeedCellRenderer,
} from './renderers'

// Static mapping object - also defined at module level
export const CELL_RENDERERS = {
  select: SelectCellRenderer,
  name: NameCellRenderer,
  size: SizeCellRenderer,
  progress: ProgressCellRenderer,
  dlspeed: DlspeedCellRenderer,
  upspeed: UpspeedCellRenderer,
  eta: EtaCellRenderer,
  ratio: RatioCellRenderer,
  state: StateCellRenderer,
  priority: PriorityCellRenderer,
  tracker: TrackerCellRenderer,
  category: CategoryCellRenderer,
  tags: TagsCellRenderer,
  added_on: AddedOnCellRenderer,
  completion_on: CompletionCellRenderer,
  last_activity: LastActivityCellRenderer,
  save_path: SavePathCellRenderer,
  downloaded: DownloadedCellRenderer,
  uploaded: UploadedCellRenderer,
  num_seeds: SeedsCellRenderer,
  num_leechs: PeersCellRenderer,
  amount_left: RemainingCellRenderer,
  time_active: TimeActiveCellRenderer,
  seeding_time: SeedingTimeCellRenderer,
} as const
